### ISSUE TITLE
I get error Module kheaders not found in directory /lib/modules/4.19.121-linuxkit

### ISSUE THREAD

**Issue by yash97** [singe/ebpf-docker-for-mac#1]
I ran 
```
python3 hello_world.py
```
I get error:
```
modprobe: FATAL: Module kheaders not found in directory /lib/modules/4.19.121-linuxkit
Unable to find kernel headers. Try rebuilding kernel with CONFIG_IKHEADERS=m (module)
chdir(/lib/modules/4.19.121-linuxkit/build): No such file or directory
Traceback (most recent call last):
  File "hello_world.py", line 14, in <module>
    b = BPF(text=prog)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 347, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>

```

**Comment by singe** [comment]
Thanks, I’ll try check it out this week. If you have time before, PRs very much appreciated.

**Comment by yash97** [comment]
oh its working seems like i made some typo :|

**Comment by steveoni** [comment]
@yash97 what was the typo ? i'm having same error

```
modprobe: FATAL: Module kheaders not found in directory /lib/modules/6.6.16-linuxkit
Unable to find kernel headers. Try rebuilding kernel with CONFIG_IKHEADERS=m (module) or installing the kernel development package for your running kernel version.
chdir(/lib/modules/6.6.16-linuxkit/build): No such file or directory
Traceback (most recent call last):
  File "/root/hello_world.py", line 14, in <module>
    b = BPF(text=prog)
        ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 479, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>
```
